version: "3.9"

services:
  tts-en_us:
    image: rhasspy/larynx:en-us
    container_name: tts-en_us
    restart: always
    ports:
      - "${TTS_EN_LOCAL_SERVER_PORT}:5002"

  tts-fr_fr:
    image: rhasspy/larynx:fr-fr
    container_name: tts-fr_fr
    restart: always
    ports:
      - "${TTS_FR_LOCAL_SERVER_PORT}:5002"
