version: "3.9"

services:
  stt-en_us:
    image: alphacep/kaldi-en:latest
    container_name: stt-en_us
    restart: always
    ports:
      - "${STT_EN_LOCAL_SERVER_PORT}:2700"

  stt-fr_fr:
    image: alphacep/kaldi-fr:latest
    container_name: stt-fr_fr
    restart: always
    ports:
      - "${STT_FR_LOCAL_SERVER_PORT}:2700"
